---
title: "Assignment3_Lina"
author: "Lina Elkjær Pedersen"
date: "2023-04-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("rlist")

pacman::p_load(tidyverse, brms, lme4, rlist)

```

*Simulation*

```{r}
set.seed <- 1981 # Defining a seed so the results are always the same
bias = 0

df = data.frame()


SimulateData <- function(n_agents, n_trials) {
  for (i in 1:n_agents) {
    FirstRating_list = list()
    SecondRating_list = list()
    Feedback_list = list()
    Other_list = list()
    Agent_list = list()
    Trial_list = list()
    #print(i)
    for (j in 1:n_trials) {
      #print(j)
      FirstRating <- round(runif(1, 1, 8), 0) #Creates a rating between 1 and 8
      Feedback <- round(runif(1, -3, 3), 0) # A feedback between -3 and 3
      while (Feedback == 1 | Feedback == -1){ #While feedback is 1 or -1, redo it
        Feedback <- round(runif(1, -3, 3), 0)
      } 
      
      Other <- FirstRating + Feedback #Other is the rating of the self + the feedback
      while (Other < 1 | Other > 8) { #While Other is outside of range of 1 and 8, redo Feedback and recalculate Other
        Feedback <- round(runif(1, -3, 3), 0)
        while (Feedback == 1 | Feedback == -1){
          Feedback <- round(runif(1, -3, 3), 0)
        } 
        Other <- FirstRating + Feedback
      }
      
      #Transforming 
      FirstRating_transformed = (((FirstRating - 1)/7)*0.8) + 0.1 #Transforming to space between 0.1 and 0.9
      Other_transformed = (((Other - 1)/7)*0.8) + 0.1
      
      #Calculating next choice
      SecondRating_transformed <- inv_logit_scaled(bias + 0.5*logit_scaled(FirstRating_transformed) + 0.5*logit_scaled(Other_transformed)) #Simple bayes. Same weight so still a simple Bayes, but we want to take an average between the two sources of evidence. Otherwise we will put too much weight on the evidence. NB bias is not transformed because we defined it on this scale already.
      
      SecondRating = round((((SecondRating_transformed - 0.1)/0.8)*7) + 1) #Transforming SecondRating back
      
      FirstRating_list = list.append(FirstRating_list, FirstRating) #Lists for df
      SecondRating_list = list.append(SecondRating_list, SecondRating)
      Feedback_list = list.append(Feedback_list, Feedback)
      Other_list = list.append(Other_list, Other)
      Agent_list = list.append(Agent_list, i)
      Trial_list = list.append(Trial_list, j)
    }
    
    df_temp <- data.frame(ID = unlist(Agent_list), Trial = unlist(Trial_list), FirstRating = unlist(FirstRating_list), Feedback = unlist(Feedback_list), SecondRating = unlist(SecondRating_list), Other = unlist(Other_list)) #Creating df by unpacking lists
    
    df <- rbind(df, df_temp)
    }

  return(df)
  }


df <- SimulateData(100, 120) 

```


```{r}
#Adding a collumn for change 
df <-  df %>% 
  mutate(Change = SecondRating - FirstRating)

```

