---
title: "Model_comparison.Rmd"
author: "Lina Elkjær Pedersen"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




**Loading data and packages**
```{r}
pacman::p_load(tidyverse, brms, lme4, rlist, rstan, cmdstanr)


df <- read_csv("all_data.csv")


#df_sub <- df %>% 
  #subset(ID == "SI201" |ID == "SI203")


df_SI <- df[ 0:6120,]
```


**Simple bayes** 
```{r}

for (i in unique(df_sub$ID)) { 
  
  df_temp <- df_sub %>% 
    subset(ID == i)
  
  data_simpleBayes <- list(
    N = nrow(df_temp),
    SecondRating = df_temp$SecondRating,
    FirstRating = df_temp$FirstRating,
    GroupRating = df_temp$GroupRating
  )

  mod_simpleBayes <- cmdstan_model("simple_bayes.stan", cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))



  samples <- mod_simpleBayes$sample(
    data = data_simpleBayes, # the data :-)
    seed = 123,  # a seed, so I always get the same results
    chains = 2,  # how many chains should I fit (to check whether they give the same results)
    parallel_chains = 2, # how many of the chains can be run in parallel?
    threads_per_chain = 2, # distribute gradient estimations within chain across multiple cores
    iter_warmup = 1000,  # warmup iterations through which hyperparameters (steps and step length) are adjusted
    iter_sampling = 2000, # total number of iterations
    refresh = 0,  # how often to show that iterations have been run
    max_treedepth = 20, # how many steps in the future to check to avoid u-turns
    adapt_delta = 0.99, # how high a learning rate to adjust hyperparameters during warmup
  )
  
  #Disabling scientific notation
  options(scipen=999)
    
  #extract summary 
  samples$summary()
  
  # assign function within loop
  assign(paste0("simple_ID_", i), samples)
  
}
  
```



**Weighted bayes** 
```{r}

for (i in unique(df_sub$ID)) { 
  
  df_temp <- df_sub %>% 
    subset(ID == i)
  
  data_weightedBayes <- list(
    N = nrow(df_temp),
    SecondRating = df_temp$SecondRating,
    FirstRating = df_temp$FirstRating,
    GroupRating = df_temp$GroupRating
  )

  mod_weightedBayes <- cmdstan_model("weighted_bayes.stan", cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))



  samples <- mod_weightedBayes$sample(
    data = data_weightedBayes, # the data :-)
    seed = 123,  # a seed, so I always get the same results
    chains = 2,  # how many chains should I fit (to check whether they give the same results)
    parallel_chains = 2, # how many of the chains can be run in parallel?
    threads_per_chain = 2, # distribute gradient estimations within chain across multiple cores
    iter_warmup = 1000,  # warmup iterations through which hyperparameters (steps and step length) are adjusted
    iter_sampling = 2000, # total number of iterations
    refresh = 0,  # how often to show that iterations have been run
    max_treedepth = 20, # how many steps in the future to check to avoid u-turns
    adapt_delta = 0.99, # how high a learning rate to adjust hyperparameters during warmup
  )
  
  #Disabling scientific notation
  options(scipen=999)
    
  #extract summary 
  samples$summary()
  
  # assign function within loop
  assign(paste0("weighted_ID_", i), samples)
  
}
```

```{r}
loo_simple_SI201 <- simple_ID_SI201$loo(cores = 4)
loo_weighted_SI201 <- weighted_ID_SI201$loo(cores = 4)


#loo_compare(loo_weighted_SI201, loo_simple_SI201)
loo_compare(loo_simple_SI201, loo_weighted_SI201)

```


**Model comparison looping through all participants** 
```{r}

for (i in unique(df_SI$ID)) { 
  
  #Fitting on 1 participant at a time
  df_temp <- df_SI %>% 
    subset(ID == i)
  
  #simple bayes
  data <- list(
    N = nrow(df_temp),
    SecondRating = df_temp$SecondRating,
    FirstRating = df_temp$FirstRating,
    GroupRating = df_temp$GroupRating
  )

  mod_simpleBayes <- cmdstan_model("simple_bayes.stan", cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
  
  mod_weightedBayes <- cmdstan_model("weighted_bayes.stan", cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))


  samples_simple <- mod_simpleBayes$sample(
    data = data, # the data :-)
    seed = 123,  # a seed, so I always get the same results
    chains = 2,  # how many chains should I fit (to check whether they give the same results)
    parallel_chains = 2, # how many of the chains can be run in parallel?
    threads_per_chain = 2, # distribute gradient estimations within chain across multiple cores
    iter_warmup = 1000,  # warmup iterations through which hyperparameters (steps and step length) are adjusted
    iter_sampling = 2000, # total number of iterations
    refresh = 0,  # how often to show that iterations have been run
    max_treedepth = 20, # how many steps in the future to check to avoid u-turns
    adapt_delta = 0.99, # how high a learning rate to adjust hyperparameters during warmup
  )
  
  samples_weighted <- mod_weightedBayes$sample(
    data = data, # the data :-)
    seed = 123,  # a seed, so I always get the same results
    chains = 2,  # how many chains should I fit (to check whether they give the same results)
    parallel_chains = 2, # how many of the chains can be run in parallel?
    threads_per_chain = 2, # distribute gradient estimations within chain across multiple cores
    iter_warmup = 1000,  # warmup iterations through which hyperparameters (steps and step length) are adjusted
    iter_sampling = 2000, # total number of iterations
    refresh = 0,  # how often to show that iterations have been run
    max_treedepth = 20, # how many steps in the future to check to avoid u-turns
    adapt_delta = 0.99, # how high a learning rate to adjust hyperparameters during warmup
  )
  
  #Disabling scientific notation
  options(scipen=999)
  
  # assign function within loop
  assign(paste0("simple_ID_", i), samples_simple)

  
  # assign function within loop
  assign(paste0("weighted_ID_", i), samples_weighted)
  
  
  loo_simple <- samples_simple$loo(cores = 4)
  loo_weighted <- samples_weighted$loo(cores = 4)


  #loo_compare(loo_weighted_SI201, loo_simple_SI201)
  model_compare <- loo_compare(loo_simple, loo_weighted)
  
  assign(paste0("loo_compare_ID_", i), model_compare)
  
}


```


**Comparing 
```{r}
#List of all elpd differences where model2 (weighted bayes) performed best
comparison_scores1<- c(-94.5,-26.5,-21.1,-37.2,-23.1,-19.4,-4.6,-31.7,-5.1,-8.0,-11.3,-36.0,-21.4,-13.8,-13.3,-31.2,-30.0,-2.3,-24.3,-3.3,-16.6,-33.3,-31.7,-49.3,-13.1,-41.6,-0.8,-17.1,-17.3,-30.8,-22.7,-4.0,-21.2,-20.1,-4.7,-1.8,-88.4,-20.1)

#List of all elpd differences where model1 (simple bayes) performed best
comparison_scores2 <- c(-0.03, -0.14)


```

